cluster.name: elasticsearch
network.host: 0.0.0.0
node.name: ${HOSTNAME}
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: [127.0.0.1]

searchguard:
    ssl.transport:
        enabled: true
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/elasticsearch-keystore.jks
        keystore_password: changeme
        truststore_type: JKS
        truststore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/truststore.jks
        truststore_password: changeme
        enforce_hostname_verification: false
    ssl.http:
        enabled: true
        # clientauth_mode: REQUIRE
        clientauth_mode: OPTIONAL
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/elasticsearch-keystore.jks
        keystore_password: changeme
        truststore_type: JKS
        truststore_filepath: /usr/share/elasticsearch/config/searchguard/ssl/truststore.jks
        truststore_password: changeme
    authcz.admin_dn:
      - "CN=elastic ,OU=devops, C=COM"
