cluster.name: ${CLUSTER_NAME}

node:
  name: ${NODE_NAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

discovery.zen:
  minimum_master_nodes: ${MINIMUM_MASTER_NODES}
  ping.unicast.hosts: ${HOSTS}
network.host: ${NETWORK_HOST}

http:
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

searchguard:
    enterprise_modules_enabled: ${SG_ENTERPRISE_ENABLED}
    restapi:
        roles_enabled:
          - "admin"
    ssl.transport:
        enabled: true
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/${NODE_NAME}-keystore.jks
        keystore_password: ${KS_PWD}
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: ${TS_PWD}
        enforce_hostname_verification: false
    ssl.http:
        enabled: ${HTTP_SSL}
        clientauth_mode: OPTIONAL
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/${NODE_NAME}-keystore.jks
        keystore_password: ${KS_PWD}
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: ${TS_PWD}
    authcz.admin_dn:
      - "CN=elastic ,OU=devops, C=COM"
