version: '2'
services:
    elasticsearch:
        build: ../
        environment:
            NODE_NAME: example
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            #HTTP_SSl: 'false'
        volumes:
            - /data/elasticsearch:/usr/share/elasticsearch/data
            - /etc/elasticsearch:/usr/share/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        network_mode: bridge
        restart: always
